wandb: Tracking run with wandb version 0.13.3
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
Error executing job with overrides: []
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/kce/miniconda3/envs/snip2/lib/python3.9/site-packages/xarray/core/dataarray.py", line 760, in _getitem_coord
    var = self._coords[key]
KeyError: 'mean_snp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kce/miniconda3/envs/snip2/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/kce/miniconda3/envs/snip2/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/faststorage/project/NLPPred/github/snip/src/snip/train_slided_autoencoder_sklearn.py", line 146, in train
    validation_X = validation.get_X().data.compute()
  File "/faststorage/project/NLPPred/github/snip/src/snip/data/dataloaders.py", line 180, in get_X
    replacement_value = self.genotype.coords[
  File "/home/kce/miniconda3/envs/snip2/lib/python3.9/site-packages/xarray/core/coordinates.py", line 369, in __getitem__
    return self._data._getitem_coord(key)
  File "/home/kce/miniconda3/envs/snip2/lib/python3.9/site-packages/xarray/core/dataarray.py", line 763, in _getitem_coord
    _, key, var = _get_virtual_variable(self._coords, key, dim_sizes)
  File "/home/kce/miniconda3/envs/snip2/lib/python3.9/site-packages/xarray/core/dataset.py", line 175, in _get_virtual_variable
    raise KeyError(key)
KeyError: 'mean_snp'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/faststorage/project/NLPPred/github/snip/src/snip/train_slided_autoencoder_sklearn.py", line 188, in main
    pool.starmap(
  File "/home/kce/miniconda3/envs/snip2/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/kce/miniconda3/envs/snip2/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 'mean_snp'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
wandb: Waiting for W&B process to finish... (failed 1).
wandb: - 0.000 MB of 0.000 MB uploaded (0.000 MB deduped)wandb: \ 0.000 MB of 0.000 MB uploaded (0.000 MB deduped)wandb: | 0.000 MB of 0.000 MB uploaded (0.000 MB deduped)wandb:                                                                                
wandb: 
wandb: Run history:
wandb: N models ‚ñÅ
wandb: 
wandb: Run summary:
wandb: N models 2
wandb: 
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /faststorage/project/NLPPred/github/snip/wandb/offline-run-20220930_202234-285jcsfx
wandb: Find logs at: ./wandb/offline-run-20220930_202234-285jcsfx/logs
